theme = "tokiwa"
languageCode = "zh-cn"
title = "CengSin PERSONAL BLOG"

[params]
useChineseFonts = true
math = true
env = "production"      # 启用 Google Analytics、DISQUS 等

[menu]
[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 1
[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "简历"
  url = "/resume/"
  weight = 3

